#
# Makefile for the bus drivers.
#

obj-$(CONFIG_OMAP_OCP2SCP)	+= omap-ocp2scp.o

# Interconnect bus driver for OMAP SoCs.
obj-$(CONFIG_OMAP_INTERCONNECT)	+= omap_l3_smx.o omap_l3_noc.o

# Interconnect pcie bus driver for Altera SoCs.
obj-$(CONFIG_ALTERA_PCIE_RP) += altera_pcie.o

